---
apiVersion: v1
kind: Service
metadata:
  name: registration-service
  namespace: vaccination-system-dev
  labels:
    svc: vms
spec:
  type: ClusterIP
  selector:
    vms: registration
  ports:
  - name: web
    protocol: TCP
    port: 8000
    targetPort: 19090